parameters:
    app.range_months: 3
    app.post.delay: 86400
    app.post.max_count: 10
    app.fun:
        Browsers:
            Mozilla Firefox: [firefox, firefox-developer-edition]
            Chromium: [chromium, google-chrome]
            Konqueror: konqueror
            Midori: midori
            GNOME Web: epiphany
        Editors:
            Vim: vim
            Emacs: emacs
            Nano: nano
            Gedit: gedit
            Kate: kate
            Kwrite: kwrite
            Vi: vi
            Mousepad: mousepad
            Leafpad: leafpad
            Geany: geany
        Desktop Environments:
            KDE SC: plasma-workspace
            GNOME: gnome-shell
            LXDE: lxde-common
            Xfce: xfdesktop
            MATE: mate-panel
            Cinnamon: cinnamon
        File Managers:
            Dolphin: dolphin
            Konqueror: konqueror
            MC: mc
            GNOME Files: nautilus
            PCManFM: pcmanfm
            Thunar: thunar
            Caja: caja
            Nemo: nemo
        Window Managers:
            Openbox: openbox
            Fluxbox: fluxbox
            I3: i3-wm
            awesome: awesome
        Shells:
            Bash: bash
            Dash: dash
            Zsh: zsh
            Fish: fish
            Tcsh: tcsh
        Graphic Chipsets:
            AMD: [xf86-video-ati, xf86-video-amdgpu]
            NVIDIA: [nvidia-utils, nvidia-390xx-utils, xf86-video-nouveau]
            Intel: xf86-video-intel
        Runtime Environment:
            PHP: php
            Ruby: ruby
            Perl: perl
            Java: java-environment-common
            Python: python
            Node.js: nodejs
            Lua: lua
            Bash: bash
