nelmio_api_doc:
    documentation:
        info:
            title: pkgstats API documentation
            version: 3.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        name_patterns:
            - ^app_api_submit
            - ^app_api_package
        disable_default_routes: true

when@dev:
    nelmio_api_doc:
        areas:
            default:
                name_patterns:
                    - ^app_api_
