version: "3.8"

services:
  cypress:
    image: cypress/included:cypress-12.12.0-node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=${CYPRESS_baseUrl:-http://nginx}
    ipc: host
    userns_mode: host
    working_dir: /app
    volumes:
      - ../app:/app:ro
      - ../app/tests/e2e:/app/tests/e2e:rw
    tmpfs:
      - /tmp
