version: "3.8"

services:
  cypress:
    image: cypress/included:cypress-12.9.0-node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=${CYPRESS_baseUrl:-http://nginx}
    ipc: host
    userns_mode: host
    working_dir: /app
    volumes:
      - ../app:/app:ro
      - ../app/tests/e2e:/app/tests/e2e:rw
    tmpfs:
      - /tmp
