version: "3.8"

services:
  cypress:
    image: cypress/included:cypress-12.15.0-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=${CYPRESS_baseUrl:-http://nginx}
    ipc: host
    userns_mode: host
    working_dir: /app
    volumes:
      - ../app:/app:ro
      - ../app/tests/e2e:/app/tests/e2e:rw
    tmpfs:
      - /tmp
