onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js
  - core-js-pure
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
nodeLinker: hoisted
